import {
  Device,
  DeviceType,
  Location,
  DeviceInterface,
  QueueTraffic,
  VpnTunnel,
  Alert,
  AlertRule,
  RepairRecord,
  ReportSchedule,
  User,
  AuditLog,
  AutoDiscoveredDevice,
  CapacityMetric,
  DashboardWidgetVisibility,
} from './types';

export const initialLocations: Location[] = [
  { id: 'loc-1', name: 'Data Center & Server Room', building: 'Gedung Utama', floor: 'Lantai 1', description: 'Rak Server & Core Network Gateway', device_count: 0 },
];

export const initialDevices: Device[] = [];

export const generateDefaultInterfaces = (
  deviceId: string,
  deviceType: DeviceType = 'router',
  baseMac: string = 'DC:2C:6E:8A:11:00',
  deviceName?: string
): DeviceInterface[] => {
  const cleanMac = baseMac && baseMac !== '00:00:00:00:00:00' ? baseMac : 'DC:2C:6E:8A:11:00';
  const macPrefix = cleanMac.length >= 14 ? cleanMac.slice(0, 14) : 'DC:2C:6E:8A:11';

  if (deviceType === 'router') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'ether1',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 16.9,
        tx_rate: 0.9399,
        fp_rx_rate: 17.4,
        fp_tx_rate: 0.9493,
        rx_packet_ps: 1801,
        tx_packet_ps: 1008,
        rx_bytes: 58491829481,
        tx_bytes: 3491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'ether2-Server',
        type: 'ethernet',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 0.3289,
        tx_rate: 6.8,
        rx_packet_ps: 536,
        tx_packet_ps: 899,
        rx_bytes: 1249182948,
        tx_bytes: 19491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'ether3-Office',
        type: 'ethernet',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 0.9856,
        tx_rate: 13.8,
        rx_packet_ps: 1016,
        tx_packet_ps: 1544,
        rx_bytes: 3491829481,
        tx_bytes: 41491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-4`,
        device_id: deviceId,
        name: 'ether4-Development',
        type: 'ethernet',
        mac_address: `${macPrefix}:04`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 1.8121,
        tx_rate: 7.2,
        rx_packet_ps: 358,
        tx_packet_ps: 846,
        rx_bytes: 5819284192,
        tx_bytes: 22491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-5`,
        device_id: deviceId,
        name: 'ether5-CCTV',
        type: 'ethernet',
        mac_address: `${macPrefix}:05`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 7.9,
        tx_rate: 0.293,
        rx_packet_ps: 993,
        tx_packet_ps: 570,
        rx_bytes: 28491829481,
        tx_bytes: 981928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-6`,
        device_id: deviceId,
        name: 'bridge-WAN',
        type: 'bridge',
        mac_address: `${macPrefix}:00`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 14.7,
        tx_rate: 0.8814,
        rx_packet_ps: 1613,
        tx_packet_ps: 958,
        rx_bytes: 49491829481,
        tx_bytes: 2849182948,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-7`,
        device_id: deviceId,
        name: 'bridge-Local',
        type: 'bridge',
        mac_address: `${macPrefix}:06`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 0.8165,
        tx_rate: 13.9,
        rx_packet_ps: 1032,
        tx_packet_ps: 1575,
        rx_bytes: 1892841928,
        tx_bytes: 38491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-8`,
        device_id: deviceId,
        name: 'bridge-Dev',
        type: 'bridge',
        mac_address: `${macPrefix}:07`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 1.7655,
        tx_rate: 6.5,
        rx_packet_ps: 359,
        tx_packet_ps: 782,
        rx_bytes: 4218920192,
        tx_bytes: 18491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-9`,
        device_id: deviceId,
        name: 'bridge-Server',
        type: 'bridge',
        mac_address: `${macPrefix}:08`,
        status: 'up',
        speed: '100 Mbps (Fast Ethernet)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 0.2353,
        tx_rate: 6.6,
        rx_packet_ps: 531,
        tx_packet_ps: 882,
        rx_bytes: 849182948,
        tx_bytes: 15491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-10`,
        device_id: deviceId,
        name: 'sfp1',
        type: 'sfp',
        mac_address: `${macPrefix}:0F`,
        status: 'down',
        speed: '1 Gbps (SFP)',
        mtu: 1500,
        l2_mtu: 1596,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-11`,
        device_id: deviceId,
        name: 'ovpn-sukowati',
        type: 'ovpn',
        mac_address: `${macPrefix}:11`,
        status: 'up',
        speed: 'Virtual Tunnel',
        mtu: 1500,
        rx_rate: 0,
        tx_rate: 0.0029,
        rx_packet_ps: 0,
        tx_packet_ps: 3,
        rx_bytes: 1024,
        tx_bytes: 148192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-12`,
        device_id: deviceId,
        name: 'pptp-guest',
        type: 'pptp',
        mac_address: `${macPrefix}:12`,
        status: 'up',
        speed: 'Virtual Tunnel',
        mtu: 1400,
        rx_rate: 0.000432,
        tx_rate: 0,
        rx_packet_ps: 1,
        tx_packet_ps: 0,
        rx_bytes: 58291,
        tx_bytes: 1024,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-13`,
        device_id: deviceId,
        name: 'vlan20',
        type: 'vlan',
        mac_address: `${macPrefix}:20`,
        status: 'down',
        speed: 'VLAN 20',
        mtu: 1500,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-14`,
        device_id: deviceId,
        name: 'VPN-CYBER',
        type: 'pptp',
        mac_address: `${macPrefix}:14`,
        status: 'down',
        speed: 'PPTP Client',
        mtu: 1400,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-15`,
        device_id: deviceId,
        name: 'VPN-CYBER-L2TP',
        type: 'l2tp',
        mac_address: `${macPrefix}:15`,
        status: 'down',
        speed: 'L2TP Client',
        mtu: 1450,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-16`,
        device_id: deviceId,
        name: 'pt vpn',
        type: 'l2tp',
        mac_address: `${macPrefix}:16`,
        status: 'down',
        speed: 'L2TP Client',
        mtu: 1450,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-17`,
        device_id: deviceId,
        name: 'pppoe-out1',
        type: 'pppoe',
        mac_address: `${macPrefix}:17`,
        status: 'down',
        speed: 'PPPoE Client',
        mtu: 1480,
        rx_rate: 0,
        tx_rate: 0,
        rx_packet_ps: 0,
        tx_packet_ps: 0,
        rx_bytes: 0,
        tx_bytes: 0,
        error_rate: 0,
      },
    ];
  }

  if (deviceType === 'switch') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'GigabitEthernet0/1 (Uplink Trunk)',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 68.5,
        tx_rate: 45.2,
        rx_bytes: 67182948192,
        tx_bytes: 49182948192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'GigabitEthernet0/2 (Server Room)',
        type: 'ethernet',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 34.1,
        tx_rate: 28.4,
        rx_bytes: 38192841928,
        tx_bytes: 31294819284,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'GigabitEthernet0/3 (Access Point)',
        type: 'ethernet',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 18.2,
        tx_rate: 8.5,
        rx_bytes: 19481928419,
        tx_bytes: 9819284192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-4`,
        device_id: deviceId,
        name: 'GigabitEthernet0/4 (CCTV NVR Feed)',
        type: 'ethernet',
        mac_address: `${macPrefix}:04`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 24.8,
        tx_rate: 1.2,
        rx_bytes: 28419284192,
        tx_bytes: 1481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-5`,
        device_id: deviceId,
        name: 'GigabitEthernet0/24 (Backup Port)',
        type: 'ethernet',
        mac_address: `${macPrefix}:24`,
        status: 'down',
        speed: '1 Gbps',
        rx_rate: 0,
        tx_rate: 0,
        rx_bytes: 1248192,
        tx_bytes: 849182,
        error_rate: 0,
      },
    ];
  }

  if (deviceType === 'access_point') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'eth0 (PoE Gigabit Uplink)',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 22.4,
        tx_rate: 8.7,
        rx_bytes: 29481928419,
        tx_bytes: 11481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'wlan1 (2.4GHz b/g/n/ax)',
        type: 'wlan',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '574 Mbps',
        rx_rate: 6.2,
        tx_rate: 2.1,
        rx_bytes: 8481928419,
        tx_bytes: 3481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'wlan2 (5GHz a/n/ac/ax)',
        type: 'wlan',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '1.2 Gbps',
        rx_rate: 16.2,
        tx_rate: 6.6,
        rx_bytes: 21000000000,
        tx_bytes: 8000000000,
        error_rate: 0,
      },
    ];
  }

  return [
    {
      id: `if-${deviceId}-1`,
      device_id: deviceId,
      name: 'eth0 (Primary Management)',
      type: 'ethernet',
      mac_address: `${macPrefix}:01`,
      status: 'up',
      speed: '1 Gbps',
      rx_rate: 15.4,
      tx_rate: 8.2,
      rx_bytes: 18491829481,
      tx_bytes: 9819284192,
      error_rate: 0,
    },
    {
      id: `if-${deviceId}-2`,
      device_id: deviceId,
      name: 'eth1 (LAN / Data Link)',
      type: 'ethernet',
      mac_address: `${macPrefix}:02`,
      status: 'up',
      speed: '1 Gbps',
      rx_rate: 12.1,
      tx_rate: 6.4,
      rx_bytes: 14819284192,
      tx_bytes: 7819284192,
      error_rate: 0,
    },
  ];
};

export const initialInterfaces: DeviceInterface[] = [];

export const initialQueues: QueueTraffic[] = [
  {
    id: 'qt-dev-1-16777216',
    device_id: 'dev-1',
    name: 'TOTAL-INTERNET',
    parent: 'global',
    packet_mark: 'no-mark',
    target: 'global',
    max_limit: '120M',
    limit_at: '120M',
    current_rate: { download: 33.2, upload: 0 },
    packet_rate: 3980,
    dropped: 0,
    priority: 1,
    queue_type: 'default',
    bytes: 11785061982,
    packets: 55073755,
    kind: 'tree',
  },
  {
    id: 'qt-dev-1-16777217',
    device_id: 'dev-1',
    name: '1. Server-CCTV',
    parent: 'TOTAL-INTERNET',
    packet_mark: 'packet-server-cctv',
    target: 'TOTAL-INTERNET',
    max_limit: '40M',
    limit_at: '25M',
    current_rate: { download: 11.4, upload: 0 },
    packet_rate: 1370,
    dropped: 0,
    priority: 2,
    queue_type: 'pcq-download-default',
    bytes: 25302552,
    packets: 160855,
    kind: 'tree',
  },
  {
    id: 'qt-dev-1-16777218',
    device_id: 'dev-1',
    name: '2. Dev-Group',
    parent: 'TOTAL-INTERNET',
    packet_mark: 'no-mark',
    target: 'TOTAL-INTERNET',
    max_limit: '50M',
    limit_at: '20M',
    current_rate: { download: 13.4, upload: 0 },
    packet_rate: 1610,
    dropped: 0,
    priority: 3,
    queue_type: 'default',
    bytes: 5216433298,
    packets: 21921525,
    kind: 'tree',
  },
  {
    id: 'qt-dev-1-16777219',
    device_id: 'dev-1',
    name: '2a. VIP-User',
    parent: '2. Dev-Group',
    packet_mark: 'packet-vip',
    target: '2. Dev-Group',
    max_limit: '40M',
    limit_at: '10M',
    current_rate: { download: 4.2, upload: 0 },
    packet_rate: 510,
    dropped: 0,
    priority: 8,
    queue_type: 'pcq-download-default',
    bytes: 0,
    packets: 0,
    kind: 'tree',
  },
  {
    id: 'qt-dev-1-16777220',
    device_id: 'dev-1',
    name: '2b. Dev-Staff',
    parent: '2. Dev-Group',
    packet_mark: 'packet-dev',
    target: '2. Dev-Group',
    max_limit: '50M',
    limit_at: '20M',
    current_rate: { download: 9.2, upload: 0 },
    packet_rate: 1100,
    dropped: 1316,
    priority: 3,
    queue_type: 'pcq-download-default',
    bytes: 5216412452,
    packets: 21921448,
    kind: 'tree',
  },
  {
    id: 'qt-dev-1-16777221',
    device_id: 'dev-1',
    name: '3. Kantor',
    parent: 'TOTAL-INTERNET',
    packet_mark: 'packet-kantor',
    target: 'TOTAL-INTERNET',
    max_limit: '40M',
    limit_at: '15M',
    current_rate: { download: 8.4, upload: 0 },
    packet_rate: 1010,
    dropped: 32365,
    priority: 5,
    queue_type: 'pcq-download-default',
    bytes: 6543230870,
    packets: 32990923,
    kind: 'tree',
  },
];

export const initialVpnTunnels: VpnTunnel[] = [];

export const initialAlerts: Alert[] = [];

export const initialAlertRules: AlertRule[] = [
  { id: 'rule-1', name: 'Peringatan Perangkat Down / Putus', metric: 'offline_status', condition: 'offline', threshold: 1, duration_seconds: 60, enabled: true, escalation_tier: 1, notify_email: true, notify_sound: true },
  { id: 'rule-2', name: 'Ambang Batas Latensi Tinggi (> 75ms)', metric: 'latency', condition: '>', threshold: 75, duration_seconds: 120, enabled: true, escalation_tier: 1, notify_email: false, notify_sound: true },
  { id: 'rule-3', name: 'Ambang Batas Beban CPU Kritis (> 85%)', metric: 'cpu_usage', condition: '>', threshold: 85, duration_seconds: 300, enabled: true, escalation_tier: 2, notify_email: true, notify_sound: true },
  { id: 'rule-4', name: 'Packet Loss Ekstrem (> 5%)', metric: 'packet_loss', condition: '>', threshold: 5, duration_seconds: 60, enabled: true, escalation_tier: 1, notify_email: true, notify_sound: true },
];

export const initialRepairRecords: RepairRecord[] = [];

export const initialReportSchedules: ReportSchedule[] = [];

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Budi Santoso, S.Kom',
    email: 'admin@kantor.go.id',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=60',
    status: 'active',
    last_login: new Date().toISOString(),
    created_at: '2026-01-01T00:00:00Z',
    phone: '+62 812-3456-7890',
  },
  {
    id: 'usr-2',
    name: 'Dimas Prakoso',
    email: 'dimas@kantor.go.id',
    role: 'petugas',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60',
    status: 'active',
    last_login: '2026-08-19T03:15:00Z',
    created_at: '2026-01-15T00:00:00Z',
    phone: '+62 813-9876-5432',
  },
];

export const initialAuditLogs: AuditLog[] = [];

export const initialAutoDiscovered: AutoDiscoveredDevice[] = [];

export const initialCapacityData: CapacityMetric[] = [];

export const initialDashboardWidgets: DashboardWidgetVisibility = {
  throughput_chart: true,
  ping_gauge: true,
  simple_queues: true,
  vpn_status: true,
  recent_alerts: true,
};


