import {
  Device,
  DeviceType,
  Location,
  DeviceInterface,
  QueueTraffic,
  VpnTunnel,
  Alert,
  AlertRule,
  RepairRecord,
  ReportSchedule,
  User,
  AuditLog,
  AutoDiscoveredDevice,
  CapacityMetric,
  AiLogAnomaly,
  LanRouteRecommendation,
  DeviceOptimizationPlan,
  AiSimulationMetrics,
  DashboardWidgetVisibility,
  AiConfig,
} from './types';

export const initialLocations: Location[] = [
  { id: 'loc-1', name: 'Gedung A - Lantai 1', building: 'Gedung A', floor: 'Lantai 1', description: 'Ruang Pelayanan, Lobby, dan Area Kerja Utama', device_count: 5 },
  { id: 'loc-2', name: 'Gedung A - Lantai 2', building: 'Gedung A', floor: 'Lantai 2', description: 'Ruang Direksi, Ruang Rapat, dan Finance', device_count: 4 },
  { id: 'loc-3', name: 'Data Center & Server Room', building: 'Gedung A', floor: 'Basement', description: 'Rak Server Utama, Core Switch, Router Gateway, UPS', device_count: 6 },
  { id: 'loc-4', name: 'Gedung B - Lantai 1', building: 'Gedung B', floor: 'Lantai 1', description: 'Gudang & Divisi Operasional Logistik', device_count: 3 },
  { id: 'loc-5', name: 'Area Outdoor & Pos Jaga', building: 'Outdoor', floor: 'Ground', description: 'Access Point Luar & CCTV perimeter', device_count: 2 },
];

export const initialDevices: Device[] = [
  {
    id: 'dev-1',
    name: 'MikroTik CCR2004 (Core Gateway)',
    type: 'router',
    ip_address: '192.168.1.1',
    mac_address: 'DC:2C:6E:8A:11:01',
    model: 'MikroTik CCR2004-16G-2S+',
    location_id: 'loc-3',
    location_name: 'Data Center & Server Room',
    is_priority: true,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-10T08:00:00Z',
    uptime: '45 hari 12 jam',
    cpu_usage: 24,
    ram_usage: 38,
    storage_usage: 18,
    temperature: 42,
    voltage: 24.1,
    latency: 2,
    packet_loss: 0,
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 380, y: 120 },
  },
  {
    id: 'dev-2',
    name: 'FortiGate 60F (Edge Firewall)',
    type: 'firewall',
    ip_address: '192.168.1.254',
    mac_address: '00:09:0F:AB:33:99',
    model: 'Fortinet FortiGate 60F',
    location_id: 'loc-3',
    location_name: 'Data Center & Server Room',
    is_priority: true,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-10T08:00:00Z',
    uptime: '62 hari 4 jam',
    cpu_usage: 31,
    ram_usage: 52,
    storage_usage: 41,
    temperature: 46,
    latency: 3,
    packet_loss: 0,
    snmp_version: 'v3',
    snmp_v3: {
      username: 'noc_admin',
      auth_protocol: 'SHA',
      auth_key: 'Secr3tAuthP@ss',
      privacy_protocol: 'AES',
      privacy_key: 'Secr3tPrivP@ss',
    },
    coordinates: { x: 220, y: 80 },
  },
  {
    id: 'dev-3',
    name: 'Cisco 2960 (Switch Distribusi DC)',
    type: 'switch',
    ip_address: '192.168.1.2',
    mac_address: '00:1E:13:B4:92:AA',
    model: 'Cisco Catalyst WS-C2960X-24TD-L',
    location_id: 'loc-3',
    location_name: 'Data Center & Server Room',
    is_priority: true,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-10T08:00:00Z',
    uptime: '45 hari 10 jam',
    cpu_usage: 18,
    ram_usage: 32,
    storage_usage: 25,
    temperature: 39,
    latency: 4,
    packet_loss: 0,
    parent_device_id: 'dev-1',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 380, y: 240 },
  },
  {
    id: 'dev-4',
    name: 'Switch Gedung A Lt.1',
    type: 'switch',
    ip_address: '192.168.1.10',
    mac_address: '00:1E:13:C2:55:12',
    model: 'Cisco Catalyst 2960-48TT',
    location_id: 'loc-1',
    location_name: 'Gedung A - Lantai 1',
    is_priority: false,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-15T09:00:00Z',
    uptime: '18 hari 6 jam',
    cpu_usage: 22,
    ram_usage: 44,
    storage_usage: 19,
    temperature: 41,
    latency: 6,
    packet_loss: 0,
    parent_device_id: 'dev-3',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 240, y: 380 },
  },
  {
    id: 'dev-5',
    name: 'Switch Gedung A Lt.2',
    type: 'switch',
    ip_address: '192.168.1.20',
    mac_address: '00:1E:13:D8:71:04',
    model: 'Cisco Catalyst 2960-24TT',
    location_id: 'loc-2',
    location_name: 'Gedung A - Lantai 2',
    is_priority: false,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-15T09:30:00Z',
    uptime: '30 hari 2 jam',
    cpu_usage: 15,
    ram_usage: 36,
    storage_usage: 20,
    temperature: 38,
    latency: 5,
    packet_loss: 0,
    parent_device_id: 'dev-3',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 520, y: 380 },
  },
  {
    id: 'dev-6',
    name: 'AP Lobby & Pelayanan Lt.1',
    type: 'access_point',
    ip_address: '192.168.10.15',
    mac_address: '74:83:C2:11:AB:60',
    model: 'UniFi U6-Pro Access Point',
    location_id: 'loc-1',
    location_name: 'Gedung A - Lantai 1',
    is_priority: true,
    status: 'warning',
    last_seen: new Date().toISOString(),
    created_at: '2026-02-01T10:00:00Z',
    uptime: '4 hari 1 jam',
    cpu_usage: 78,
    ram_usage: 84,
    storage_usage: 55,
    temperature: 53,
    latency: 82,
    packet_loss: 8.5,
    parent_device_id: 'dev-4',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 140, y: 500 },
  },
  {
    id: 'dev-7',
    name: 'AP Ruang Rapat Lt.2',
    type: 'access_point',
    ip_address: '192.168.10.25',
    mac_address: '74:83:C2:22:CD:71',
    model: 'UniFi U6-Lite Access Point',
    location_id: 'loc-2',
    location_name: 'Gedung A - Lantai 2',
    is_priority: false,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-02-01T10:30:00Z',
    uptime: '12 hari 8 jam',
    cpu_usage: 28,
    ram_usage: 42,
    storage_usage: 30,
    temperature: 44,
    latency: 9,
    packet_loss: 0,
    parent_device_id: 'dev-5',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 620, y: 500 },
  },
  {
    id: 'dev-8',
    name: 'Dell PowerEdge R740 (Server App & NMS)',
    type: 'server',
    ip_address: '192.168.1.100',
    mac_address: '4C:D9:8F:72:EE:90',
    model: 'Dell PowerEdge R740 Xeon Gold',
    location_id: 'loc-3',
    location_name: 'Data Center & Server Room',
    is_priority: true,
    status: 'online',
    last_seen: new Date().toISOString(),
    created_at: '2026-01-05T08:00:00Z',
    uptime: '90 hari 18 jam',
    cpu_usage: 42,
    ram_usage: 68,
    storage_usage: 58,
    temperature: 36,
    latency: 1,
    packet_loss: 0,
    parent_device_id: 'dev-3',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 550, y: 180 },
  },
  {
    id: 'dev-9',
    name: 'Switch Distribusi Gedung B',
    type: 'switch',
    ip_address: '192.168.1.30',
    mac_address: '00:1E:13:EE:90:77',
    model: 'Cisco Catalyst 2960-24TT',
    location_id: 'loc-4',
    location_name: 'Gedung B - Lantai 1',
    is_priority: false,
    status: 'offline',
    last_seen: '2026-08-19T02:15:00Z',
    created_at: '2026-01-20T11:00:00Z',
    uptime: '0 menit (Down)',
    cpu_usage: 0,
    ram_usage: 0,
    storage_usage: 0,
    temperature: 0,
    latency: 999,
    packet_loss: 100,
    parent_device_id: 'dev-3',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 700, y: 280 },
  },
  {
    id: 'dev-10',
    name: 'AP Gudang Logistik B',
    type: 'access_point',
    ip_address: '192.168.10.40',
    mac_address: '74:83:C2:55:FF:11',
    model: 'UniFi U6-Lite Access Point',
    location_id: 'loc-4',
    location_name: 'Gedung B - Lantai 1',
    is_priority: false,
    status: 'unreachable',
    last_seen: '2026-08-19T02:15:00Z',
    created_at: '2026-01-20T11:30:00Z',
    uptime: 'Unreachable (Parent Down)',
    cpu_usage: 0,
    ram_usage: 0,
    storage_usage: 0,
    temperature: 0,
    latency: 999,
    packet_loss: 100,
    parent_device_id: 'dev-9',
    snmp_version: 'v2c',
    snmp_community: 'public_nms',
    coordinates: { x: 780, y: 440 },
  },
];

export const generateDefaultInterfaces = (
  deviceId: string,
  deviceType: DeviceType = 'router',
  baseMac: string = 'DC:2C:6E:8A:11:00',
  deviceName?: string
): DeviceInterface[] => {
  const cleanMac = baseMac && baseMac !== '00:00:00:00:00:00' ? baseMac : 'DC:2C:6E:8A:11:00';
  const macPrefix = cleanMac.length >= 14 ? cleanMac.slice(0, 14) : 'DC:2C:6E:8A:11';

  if (deviceType === 'router') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'ether1-WAN-Indihome (Gateway)',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 45.8,
        tx_rate: 18.2,
        rx_bytes: 58491829481,
        tx_bytes: 19829481928,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'ether2-LAN-Utama (Bridge)',
        type: 'ethernet',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 28.4,
        tx_rate: 12.6,
        rx_bytes: 34819284192,
        tx_bytes: 14819284192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'ether3-LAN-Staff & Ruang Kerja',
        type: 'ethernet',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 14.1,
        tx_rate: 6.8,
        rx_bytes: 18491829481,
        tx_bytes: 8491829481,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-4`,
        device_id: deviceId,
        name: 'ether4-Hotspot-WiFi',
        type: 'ethernet',
        mac_address: `${macPrefix}:04`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 8.5,
        tx_rate: 3.2,
        rx_bytes: 9819284192,
        tx_bytes: 4219284192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-5`,
        device_id: deviceId,
        name: 'sfp-plus1-Trunk-Core (Fiber Optic)',
        type: 'sfp',
        mac_address: `${macPrefix}:0F`,
        status: 'up',
        speed: '10 Gbps',
        rx_rate: 74.2,
        tx_rate: 58.6,
        rx_bytes: 89481928419,
        tx_bytes: 72918294819,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-6`,
        device_id: deviceId,
        name: 'bridge1-LAN-Local',
        type: 'bridge',
        mac_address: `${macPrefix}:00`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 51.0,
        tx_rate: 22.6,
        rx_bytes: 63129481928,
        tx_bytes: 27319284192,
        error_rate: 0,
      },
    ];
  }

  if (deviceType === 'switch') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'GigabitEthernet0/1 (Uplink Trunk)',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 68.5,
        tx_rate: 45.2,
        rx_bytes: 67182948192,
        tx_bytes: 49182948192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'GigabitEthernet0/2 (Server Room)',
        type: 'ethernet',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 34.1,
        tx_rate: 28.4,
        rx_bytes: 38192841928,
        tx_bytes: 31294819284,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'GigabitEthernet0/3 (Access Point)',
        type: 'ethernet',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 18.2,
        tx_rate: 8.5,
        rx_bytes: 19481928419,
        tx_bytes: 9819284192,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-4`,
        device_id: deviceId,
        name: 'GigabitEthernet0/4 (CCTV NVR Feed)',
        type: 'ethernet',
        mac_address: `${macPrefix}:04`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 24.8,
        tx_rate: 1.2,
        rx_bytes: 28419284192,
        tx_bytes: 1481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-5`,
        device_id: deviceId,
        name: 'GigabitEthernet0/24 (Backup Port)',
        type: 'ethernet',
        mac_address: `${macPrefix}:24`,
        status: 'down',
        speed: '1 Gbps',
        rx_rate: 0,
        tx_rate: 0,
        rx_bytes: 1248192,
        tx_bytes: 849182,
        error_rate: 0,
      },
    ];
  }

  if (deviceType === 'access_point') {
    return [
      {
        id: `if-${deviceId}-1`,
        device_id: deviceId,
        name: 'eth0 (PoE Gigabit Uplink)',
        type: 'ethernet',
        mac_address: `${macPrefix}:01`,
        status: 'up',
        speed: '1 Gbps',
        rx_rate: 22.4,
        tx_rate: 8.7,
        rx_bytes: 29481928419,
        tx_bytes: 11481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-2`,
        device_id: deviceId,
        name: 'wlan1 (2.4GHz b/g/n/ax)',
        type: 'wlan',
        mac_address: `${macPrefix}:02`,
        status: 'up',
        speed: '574 Mbps',
        rx_rate: 6.2,
        tx_rate: 2.1,
        rx_bytes: 8481928419,
        tx_bytes: 3481928419,
        error_rate: 0,
      },
      {
        id: `if-${deviceId}-3`,
        device_id: deviceId,
        name: 'wlan2 (5GHz a/n/ac/ax)',
        type: 'wlan',
        mac_address: `${macPrefix}:03`,
        status: 'up',
        speed: '1.2 Gbps',
        rx_rate: 16.2,
        tx_rate: 6.6,
        rx_bytes: 21000000000,
        tx_bytes: 8000000000,
        error_rate: 0,
      },
    ];
  }

  return [
    {
      id: `if-${deviceId}-1`,
      device_id: deviceId,
      name: 'eth0 (Primary Management)',
      type: 'ethernet',
      mac_address: `${macPrefix}:01`,
      status: 'up',
      speed: '1 Gbps',
      rx_rate: 15.4,
      tx_rate: 8.2,
      rx_bytes: 18491829481,
      tx_bytes: 9819284192,
      error_rate: 0,
    },
    {
      id: `if-${deviceId}-2`,
      device_id: deviceId,
      name: 'eth1 (LAN / Data Link)',
      type: 'ethernet',
      mac_address: `${macPrefix}:02`,
      status: 'up',
      speed: '1 Gbps',
      rx_rate: 12.1,
      tx_rate: 6.4,
      rx_bytes: 14819284192,
      tx_bytes: 7819284192,
      error_rate: 0,
    },
  ];
};

export const initialInterfaces: DeviceInterface[] = [
  ...generateDefaultInterfaces('dev-1', 'router', 'DC:2C:6E:8A:11:00'),
  ...generateDefaultInterfaces('dev-2', 'router', '48:8F:5A:90:12:00'),
  ...generateDefaultInterfaces('dev-3', 'switch', '00:1E:13:EE:44:00'),
  ...generateDefaultInterfaces('dev-4', 'switch', '00:1E:13:EE:55:00'),
  ...generateDefaultInterfaces('dev-5', 'switch', '00:1E:13:EE:66:00'),
  ...generateDefaultInterfaces('dev-6', 'access_point', '74:83:C2:11:AA:00'),
  ...generateDefaultInterfaces('dev-7', 'access_point', '74:83:C2:22:BB:00'),
  ...generateDefaultInterfaces('dev-8', 'server', 'E4:5F:01:33:CC:00'),
  ...generateDefaultInterfaces('dev-9', 'switch', '00:1E:13:EE:90:00'),
  ...generateDefaultInterfaces('dev-10', 'access_point', '74:83:C2:55:FF:00'),
];

export const initialQueues: QueueTraffic[] = [
  { id: 'q-1', device_id: 'dev-1', name: '01. Queue VIP Direksi & Management', target: '192.168.100.0/24', max_limit: '100M/100M', current_rate: { upload: 14.2, download: 38.6 }, packet_rate: 2450, dropped: 0 },
  { id: 'q-2', device_id: 'dev-1', name: '02. Queue Staff & Operasional Lt.1', target: '192.168.10.0/24', max_limit: '80M/80M', current_rate: { upload: 18.5, download: 64.2 }, packet_rate: 4120, dropped: 12 },
  { id: 'q-3', device_id: 'dev-1', name: '03. Queue Staff & Operasional Lt.2', target: '192.168.20.0/24', max_limit: '80M/80M', current_rate: { upload: 11.2, download: 45.7 }, packet_rate: 3100, dropped: 2 },
  { id: 'q-4', device_id: 'dev-1', name: '04. Queue Guest WiFi Publik', target: '192.168.200.0/24', max_limit: '30M/30M', current_rate: { upload: 6.8, download: 28.9 }, packet_rate: 1890, dropped: 86 },
  { id: 'q-5', device_id: 'dev-1', name: '05. Queue CCTV Streaming System', target: '192.168.50.0/24', max_limit: '50M/50M', current_rate: { upload: 28.1, download: 2.4 }, packet_rate: 3400, dropped: 0 },
];

export const initialVpnTunnels: VpnTunnel[] = [
  { id: 'vpn-1', device_id: 'dev-1', name: 'WG-Cabang-Surabaya', type: 'wireguard', user: 'peer-sby-core', remote_ip: '180.252.11.45', status: 'connected', uptime: '14 hari 8 jam', bytes_in: 28419284129, bytes_out: 41928419284 },
  { id: 'vpn-2', device_id: 'dev-1', name: 'L2TP-Petugas-Lapangan-1', type: 'l2tp', user: 'dimas_field', remote_ip: '114.124.90.18', status: 'connected', uptime: '3 jam 42 menit', bytes_in: 491829481, bytes_out: 981294819 },
  { id: 'vpn-3', device_id: 'dev-1', name: 'L2TP-Petugas-Lapangan-2', type: 'l2tp', user: 'siti_field', remote_ip: '114.124.91.22', status: 'disconnected', uptime: 'Offline', bytes_in: 12481928, bytes_out: 34819284 },
  { id: 'vpn-4', device_id: 'dev-1', name: 'IPsec-Backup-DC', type: 'ipsec', user: 'ipsec-peer-dc2', remote_ip: '202.158.40.12', status: 'connected', uptime: '45 hari 10 jam', bytes_in: 129481928412, bytes_out: 148192841928 },
];

export const initialAlerts: Alert[] = [
  {
    id: 'alt-1',
    device_id: 'dev-9',
    device_name: 'Switch Distribusi Gedung B',
    ip_address: '192.168.1.30',
    message: 'Perangkat tidak merespons ICMP Ping (Offline / Power Loss terdeteksi).',
    severity: 'critical',
    triggered_at: '2026-08-19T02:15:00Z',
    acknowledged: false,
  },
  {
    id: 'alt-2',
    device_id: 'dev-6',
    device_name: 'AP Lobby & Pelayanan Lt.1',
    ip_address: '192.168.10.15',
    message: 'Latensi tinggi terdeteksi (82 ms) dan Packet Loss mencapai 8.5%.',
    severity: 'warning',
    triggered_at: '2026-08-19T03:30:00Z',
    acknowledged: true,
    acknowledged_by: 'Dimas Prakoso',
  },
  {
    id: 'alt-3',
    device_id: 'dev-1',
    device_name: 'MikroTik CCR2004 (Core Gateway)',
    ip_address: '192.168.1.1',
    message: 'Throughput WAN Indihome melebihi 85% kapasitas kontrak selama 10 menit berturut-turut.',
    severity: 'info',
    triggered_at: '2026-08-19T03:00:00Z',
    acknowledged: true,
    acknowledged_by: 'Budi Santoso',
  },
];

export const initialAlertRules: AlertRule[] = [
  { id: 'rule-1', name: 'Peringatan Perangkat Down / Putus', metric: 'offline_status', condition: 'offline', threshold: 1, duration_seconds: 60, enabled: true, escalation_tier: 1, notify_email: true, notify_sound: true },
  { id: 'rule-2', name: 'Ambang Batas Latensi Tinggi (> 75ms)', metric: 'latency', condition: '>', threshold: 75, duration_seconds: 120, enabled: true, escalation_tier: 1, notify_email: false, notify_sound: true },
  { id: 'rule-3', name: 'Ambang Batas Beban CPU Kritis (> 85%)', metric: 'cpu_usage', condition: '>', threshold: 85, duration_seconds: 300, enabled: true, escalation_tier: 2, notify_email: true, notify_sound: true },
  { id: 'rule-4', name: 'Packet Loss Ekstrem (> 5%)', metric: 'packet_loss', condition: '>', threshold: 5, duration_seconds: 60, enabled: true, escalation_tier: 1, notify_email: true, notify_sound: true },
];

export const initialRepairRecords: RepairRecord[] = [
  {
    id: 'rep-1',
    ticket_code: 'TKT-2026-08-001',
    device_id: 'dev-4',
    device_name: 'Switch Gedung A Lt.1',
    ip_address: '192.168.1.10',
    user_id: 'usr-2',
    user_name: 'Dimas Prakoso',
    problem: 'Port 14 flapping terus menerus dan indikator LED orange berkedip.',
    action: 'Mengganti kabel patch cord UTP Cat6 dari switch ke wallplate dan mere-crimping konektor RJ45.',
    result: 'Port stabil di link speed 1 Gbps Full Duplex tanpa packet drop.',
    status: 'selesai',
    photo_urls: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&auto=format&fit=crop&q=60'],
    created_at: '2026-08-15T09:30:00Z',
    updated_at: '2026-08-15T11:15:00Z',
  },
  {
    id: 'rep-2',
    ticket_code: 'TKT-2026-08-002',
    device_id: 'dev-9',
    device_name: 'Switch Distribusi Gedung B',
    ip_address: '192.168.1.30',
    user_id: 'usr-2',
    user_name: 'Dimas Prakoso',
    problem: 'Perangkat mati mendadak setelah pemadaman genset.',
    action: 'Pemeriksaan suplai daya PSU dan kabel power di panel rack Gedung B.',
    result: 'Sedang menunggu pengujian modul adaptor cadangan.',
    status: 'berjalan',
    photo_urls: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=60'],
    created_at: '2026-08-19T02:30:00Z',
    updated_at: '2026-08-19T03:10:00Z',
  },
  {
    id: 'rep-3',
    ticket_code: 'TKT-2026-08-003',
    device_id: 'dev-6',
    device_name: 'AP Lobby & Pelayanan Lt.1',
    ip_address: '192.168.10.15',
    user_id: 'usr-3',
    user_name: 'Siti Rahma',
    problem: 'Klien mengeluhkan koneksi lambat dan latensi melonjak saat jam pelayanan ramai.',
    action: 'Mengubah channel 5GHz ke DFS Channel 52 dan menurunkan transmit power 2.4GHz untuk mengurangi interferensi.',
    result: 'Interferensi berkurang dan utilisasi kanal kembali normal di 45%.',
    status: 'selesai',
    photo_urls: ['https://images.unsplash.com/photo-1563770660941-20978e870e26?w=500&auto=format&fit=crop&q=60'],
    created_at: '2026-08-17T14:00:00Z',
    updated_at: '2026-08-17T15:30:00Z',
  },
];

export const initialReportSchedules: ReportSchedule[] = [
  {
    id: 'sch-1',
    name: 'Laporan Ketersediaan SLA & Uptime Harian',
    frequency: 'harian',
    format: 'pdf',
    recipients: ['pimpinan_it@kantor.go.id', 'noc_team@kantor.go.id'],
    created_by: 'Budi Santoso',
    last_sent_at: '2026-08-18T23:59:00Z',
    next_run_at: '2026-08-19T23:59:00Z',
    enabled: true,
  },
  {
    id: 'sch-2',
    name: 'Laporan Mingguan Insiden & Utilisasi Bandwidth',
    frequency: 'mingguan',
    format: 'excel',
    recipients: ['manager_it@kantor.go.id'],
    created_by: 'Budi Santoso',
    last_sent_at: '2026-08-12T00:00:00Z',
    next_run_at: '2026-08-19T00:00:00Z',
    enabled: true,
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Budi Santoso, S.Kom',
    email: 'admin@kantor.go.id',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=60',
    status: 'active',
    last_login: new Date().toISOString(),
    created_at: '2026-01-01T00:00:00Z',
    phone: '+62 812-3456-7890',
  },
  {
    id: 'usr-2',
    name: 'Dimas Prakoso',
    email: 'dimas@kantor.go.id',
    role: 'petugas',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60',
    status: 'active',
    last_login: '2026-08-19T03:15:00Z',
    created_at: '2026-01-15T00:00:00Z',
    phone: '+62 813-9876-5432',
  },
  {
    id: 'usr-3',
    name: 'Siti Rahma',
    email: 'siti@kantor.go.id',
    role: 'petugas',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=60',
    status: 'active',
    last_login: '2026-08-18T16:45:00Z',
    created_at: '2026-02-01T00:00:00Z',
    phone: '+62 811-2345-6789',
  },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'aud-1', user_id: 'usr-1', user_name: 'Budi Santoso', user_role: 'admin', action: 'LOGIN', details: 'Berhasil masuk ke aplikasi NMS dari browser Chrome Windows', ip_address: '192.168.1.105', timestamp: '2026-08-19T03:00:00Z' },
  { id: 'aud-2', user_id: 'usr-2', user_name: 'Dimas Prakoso', user_role: 'petugas', action: 'ACKNOWLEDGE_ALERT', details: 'Menandai alert ID #alt-2 (AP Lobby Lt.1) sebagai ditindaklanjuti', ip_address: '192.168.1.112', timestamp: '2026-08-19T03:32:00Z' },
  { id: 'aud-3', user_id: 'usr-2', user_name: 'Dimas Prakoso', user_role: 'petugas', action: 'CREATE_REPAIR_RECORD', details: 'Menambahkan tiket perbaikan TKT-2026-08-002 untuk Switch Gedung B', ip_address: '192.168.1.112', timestamp: '2026-08-19T02:30:00Z' },
  { id: 'aud-4', user_id: 'usr-1', user_name: 'Budi Santoso', user_role: 'admin', action: 'PING_TEST', details: 'Menjalankan uji koneksi ICMP ke AP Lobby Lt.1 (192.168.10.15)', ip_address: '192.168.1.105', timestamp: '2026-08-19T01:45:00Z' },
  { id: 'aud-5', user_id: 'usr-1', user_name: 'Budi Santoso', user_role: 'admin', action: 'UPDATE_SNMP_CONFIG', details: 'Memperbarui community string SNMP v2c pada MikroTik CCR2004', ip_address: '192.168.1.105', timestamp: '2026-08-18T10:20:00Z' },
];

export const initialAutoDiscovered: AutoDiscoveredDevice[] = [
  { id: 'dsc-1', ip: '192.168.1.45', mac: 'B8:27:EB:A1:88:99', suggested_name: 'MikroTik RB750Gr3 (Pos Jaga)', type: 'router', snmp_detected: true, vendor: 'MikroTik', response_time: 4, status: 'new', discovered_at: '2026-08-19T03:50:00Z' },
  { id: 'dsc-2', ip: '192.168.10.88', mac: '74:83:C2:99:11:00', suggested_name: 'UniFi AP Cafe Area', type: 'access_point', snmp_detected: true, vendor: 'Ubiquiti Networks', response_time: 7, status: 'new', discovered_at: '2026-08-19T03:51:00Z' },
  { id: 'dsc-3', ip: '192.168.1.150', mac: 'E4:5F:01:22:90:33', suggested_name: 'Synology NAS Storage 8TB', type: 'server', snmp_detected: true, vendor: 'Synology Inc.', response_time: 2, status: 'new', discovered_at: '2026-08-19T03:52:00Z' },
];

export const initialCapacityData: CapacityMetric[] = [
  { date: 'Mar 2026', bandwidth_used_mbps: 180, bandwidth_capacity_mbps: 500, storage_used_gb: 1200, storage_capacity_gb: 4000 },
  { date: 'Apr 2026', bandwidth_used_mbps: 220, bandwidth_capacity_mbps: 500, storage_used_gb: 1450, storage_capacity_gb: 4000 },
  { date: 'Mei 2026', bandwidth_used_mbps: 260, bandwidth_capacity_mbps: 500, storage_used_gb: 1750, storage_capacity_gb: 4000 },
  { date: 'Jun 2026', bandwidth_used_mbps: 310, bandwidth_capacity_mbps: 500, storage_used_gb: 2100, storage_capacity_gb: 4000 },
  { date: 'Jul 2026', bandwidth_used_mbps: 370, bandwidth_capacity_mbps: 500, storage_used_gb: 2500, storage_capacity_gb: 4000 },
  { date: 'Agu 2026 (Kini)', bandwidth_used_mbps: 410, bandwidth_capacity_mbps: 500, storage_used_gb: 2900, storage_capacity_gb: 4000 },
  { date: 'Sep 2026 (Prediksi)', bandwidth_used_mbps: 460, bandwidth_capacity_mbps: 500, storage_used_gb: 3300, storage_capacity_gb: 4000, predicted: true },
  { date: 'Okt 2026 (Prediksi)', bandwidth_used_mbps: 510, bandwidth_capacity_mbps: 500, storage_used_gb: 3750, storage_capacity_gb: 4000, predicted: true },
  { date: 'Nov 2026 (Prediksi)', bandwidth_used_mbps: 560, bandwidth_capacity_mbps: 500, storage_used_gb: 4150, storage_capacity_gb: 4000, predicted: true },
];

// ----------------------------------------------------
// FASE 6 — MOCK DATA UNTUK PENGOPTIMALAN JARINGAN AI
// ----------------------------------------------------

export const initialAiLogAnomalies: AiLogAnomaly[] = [
  {
    id: 'anom-1',
    timestamp: '2026-08-19T03:42:15Z',
    source_device: 'MikroTik CCR2004 (192.168.1.1)',
    category: 'queue_congestion',
    severity: 'high',
    title: 'Bottleneck Bandwidth Subnet Staff (192.168.10.0/24)',
    description: 'Terjadi antrean paket berulang pada Queue Staff Lt.1 yang mencapai batas 80M selama jam kerja puncak, memicu packet drop 12 pkts/s.',
    log_sample: 'system,queue,warning queue Staff-Lt1 max-limit reached, packet dropped 124 packets in 60s',
    root_cause: 'Penggunaan bandwidth streaming video resolusi tinggi dan download file CAD serentak oleh 45 host.',
    impact: 'Latensi melonjak dari 4ms menjadi 48ms untuk seluruh staf operasional di Lantai 1.',
  },
  {
    id: 'anom-2',
    timestamp: '2026-08-19T03:20:00Z',
    source_device: 'Cisco 2960 Switch Distribusi (192.168.1.2)',
    category: 'interface_flap',
    severity: 'medium',
    title: 'Interface Flap pada Port GigabitEthernet0/24 (Trunk Gedung B)',
    description: 'Port trunk menuju switch Gedung B mengalami link status flap (down/up) sebanyak 4 kali dalam kurun waktu 30 menit.',
    log_sample: '%LINK-3-UPDOWN: Interface GigabitEthernet0/24, changed state to down / state to up',
    root_cause: 'Konektor patch cord RJ45 kendor atau fluktuasi daya PoE pada switch ujung Gedung B.',
    impact: 'Koneksi perangkat di Gedung B terputus sementara selama interval negosiasi STP (30-50 detik).',
  },
  {
    id: 'anom-3',
    timestamp: '2026-08-19T02:15:30Z',
    source_device: 'FortiGate 100F (192.168.1.254)',
    category: 'firewall_drop',
    severity: 'low',
    title: 'Anomali Port Scanning TCP/UDP dari IP Lokal 192.168.10.95',
    description: 'Firewall memblokir 2.400 koneksi SYN/ACK mencurigakan ke port 445 dan 3389 dari satu host lokal.',
    log_sample: 'date=2026-08-19 time=02:15:30 devname="FGT100F" action="deny" srcip=192.168.10.95 dstip=192.168.1.100 dstport=445 msg="Policy drop"',
    root_cause: 'Kemungkinan malware/adware pada laptop staf yang memindai server internal SMB.',
    impact: 'Trafik lokal meningkat 15%, potensi ancaman keamanan jika tidak diisolasi.',
  },
];

export const initialLanRouteRecommendations: LanRouteRecommendation[] = [
  {
    id: 'route-rec-1',
    title: 'Isolasi & Offload Trafik CCTV NVR ke VLAN 40 Dedicated',
    target_subnet: '192.168.40.0/24 (Subnet CCTV & Streaming)',
    current_route: 'Trafik 16 kamera CCTV berjalan di VLAN 10 bersama trafik PC Staf Operasional.',
    recommended_route: 'Pindahkan port NVR ke Interface SFP-Plus2 (VLAN 40) dengan FastTrack Routing langsung ke Server Storage.',
    current_bottleneck: 'Kamera CCTV memakan throughput konstan 32 Mbps di switch distribusi lantai 1.',
    expected_improvement: 'Mengurangi beban trunk switch hingga 40% dan mengeliminasi packet drop pada PC kerja staf.',
    vlan_id: 40,
    priority: 'critical',
    status: 'pending',
  },
  {
    id: 'route-rec-2',
    title: 'Aktivasi MikroTik FastPath & Hardware Offloading pada Switch Bridge',
    target_subnet: '192.168.1.0/24 (LAN Core)',
    current_route: 'Semua paket LAN antar subnet di-inspect oleh CPU MikroTik CCR2004 via software routing.',
    recommended_route: 'Aktifkan IP FastTrack Rule dan L3 Hardware Offloading (L3HW) pada bridge VLAN.',
    current_bottleneck: 'CPU load router utama mencapai 65% saat jam kerja puncak transfer file antar divisi.',
    expected_improvement: 'Menurunkan CPU Load gateway dari 65% menjadi 18%, dan meningkatkan throughput LAN hingga 3x lipat.',
    priority: 'recommended',
    status: 'pending',
  },
  {
    id: 'route-rec-3',
    title: 'Pemberian Prioritas QoS DSCP EF (Expedited Forwarding) untuk VoIP & Zoom',
    target_subnet: '192.168.20.0/24 (Ruang Direksi & Meeting)',
    current_route: 'Paket video conference diperlakukan sebagai antrean Default Best Effort (Prioritas 8).',
    recommended_route: 'Terapkan Mangle Rule DSCP 46 dengan Simple Queue Tree Prioritas 1 (Guaranteed 20 Mbps).',
    current_bottleneck: 'Suara putus-putus dan frame drop saat rapat online bersamaan dengan jam upload laporan staf.',
    expected_improvement: 'Jitter berkurang hingga < 2ms dan latensi VoIP konsisten di bawah 5ms.',
    priority: 'recommended',
    status: 'pending',
  },
];

export const initialDeviceOptimizationPlans: DeviceOptimizationPlan[] = [
  {
    id: 'plan-1',
    device_name: 'MikroTik CCR2004 (Core Gateway)',
    device_ip: '192.168.1.1',
    category: 'qos_queue',
    title: 'Penerapan PCQ (Per Connection Queueing) Adaptif pada Subnet Staff',
    description: 'Mengubah algoritma FIFO menjadi PCQ dinamis agar pembagian bandwidth antar 45 user merata secara otomatis tanpa membebani router.',
    impact_score: 35,
    cli_script: `# Skrip Optimasi QoS PCQ MikroTik RouterOS
/queue type
add name="PCQ-Download-Staff" kind=pcq pcq-rate=15M pcq-classifier=dst-address
add name="PCQ-Upload-Staff" kind=pcq pcq-rate=5M pcq-classifier=src-address

/queue simple
set [find name="02. Queue Staff & Operasional Lt.1"] queue=PCQ-Upload-Staff/PCQ-Download-Staff priority=5/5
/log info message="[AI-Optimizer] PCQ Staff Adaptive Queue Berhasil Diterapkan"`,
    applied: false,
  },
  {
    id: 'plan-2',
    device_name: 'MikroTik CCR2004 (Core Gateway)',
    device_ip: '192.168.1.1',
    category: 'fasttrack_routing',
    title: 'Aktivasi IP FastTrack Connection untuk Mengurangi Beban CPU',
    description: 'Mengizinkan paket koneksi yang sudah establish dan related melewati CPU firewall secara cepat (bypass CPU processing).',
    impact_score: 45,
    cli_script: `# Skrip FastTrack Bypass Connection
/ip firewall filter
add chain=forward action=fasttrack-connection connection-state=established,related comment="[AI-Optimizer] FastTrack Established Connections" place-before=1
add chain=forward action=accept connection-state=established,related comment="Accept Established/Related" place-before=2
/log info message="[AI-Optimizer] FastTrack Connection Active"`,
    applied: false,
  },
  {
    id: 'plan-3',
    device_name: 'FortiGate 100F (Edge Firewall)',
    device_ip: '192.168.1.254',
    category: 'firewall_security',
    title: 'Quarantine Policy Otomatis untuk Host Terindikasi Malware (192.168.10.95)',
    description: 'Mengisolasi IP yang melakukan port scanning lokal dari akses server internal dan hanya mengizinkan akses web terbatas.',
    impact_score: 20,
    cli_script: `# Skrip FortiGate CLI Quarantine Rule
config firewall address
    edit "QUARANTINE_IP_192.168.10.95"
        set subnet 192.168.10.95 255.255.255.255
    next
end
config firewall policy
    edit 99
        set name "AI_QUARANTINE_ISOLATION"
        set srcintf "lan"
        set dstintf "internal_servers"
        set srcaddr "QUARANTINE_IP_192.168.10.95"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
    next
end`,
    applied: false,
  },
];

export const initialAiSimulationMetrics: AiSimulationMetrics = {
  current_avg_latency: 18.5,
  predicted_avg_latency: 6.2,
  current_packet_loss: 1.8,
  predicted_packet_loss: 0.0,
  current_cpu_peak: 68,
  predicted_cpu_peak: 24,
  network_health_score: 76,
  predicted_health_score: 98,
};

export const initialDashboardWidgets: DashboardWidgetVisibility = {
  throughput_chart: true,
  ai_insights: true,
  ping_gauge: true,
  simple_queues: true,
  vpn_status: true,
  recent_alerts: true,
};

export const initialAiConfig: AiConfig = {
  provider: 'google_gemini',
  model: 'gemini-2.5-flash',
  api_key: 'AIzaSyD-NOC-NMS-DEMO-SECURE-KEY-9948271',
  custom_endpoint: '',
  temperature: 0.2,
  max_tokens: 4096,
  auto_scan_enabled: true,
  auto_scan_interval_minutes: 15,
  auto_generate_scripts: true,
  notify_on_anomaly: true,
  connection_status: 'connected',
  last_tested_at: '2026-08-19T03:30:00Z',
  response_time_ms: 215,
};

