/**
 * RouterOS Script Generator & Syntax Safety Linter
 * Generates production-ready, safe MikroTik CLI scripts for QoS, Firewall, Failover, and Optimization.
 */

export interface GeneratedScript {
  id: string;
  title: string;
  category: 'qos' | 'firewall' | 'optimization' | 'failover' | 'maintenance';
  description: string;
  script: string;
  safetyLevel: 'safe' | 'medium_risk' | 'high_risk';
  tags: string[];
  explanation: string[];
}

/**
 * Generate a Queue Tree PCQ Dynamic Bandwidth Management Script for MikroTik RouterOS
 */
export function generateQosPcqScript(options: {
  wanInterface?: string;
  totalDownloadMbps: number;
  totalUploadMbps: number;
  lanSubnet?: string;
}): GeneratedScript {
  const wan = options.wanInterface || 'ether1';
  const dl = Math.max(1, options.totalDownloadMbps);
  const up = Math.max(1, options.totalUploadMbps);
  const lan = options.lanSubnet || '192.168.100.0/24';

  const script = `# ================================================================
# MIKROTIK ROUTEROS - SMART QUEUE TREE PCQ (DYNAMIC SUB-SHAPING)
# Target Subnet : ${lan}
# WAN Uplink    : ${wan} (DL: ${dl}M / UL: ${up}M)
# Generated by  : NMS-NOC AI Engine
# ================================================================

# 1. CREATE PCQ QUEUE TYPES (FAIR PER-CLIENT BANDWIDTH DISTRIBUTION)
/queue type
add name="PCQ_Download_Client" kind=pcq pcq-rate=0 pcq-limit=50KiB pcq-total-limit=2000KiB pcq-classifier=dst-address
add name="PCQ_Upload_Client"   kind=pcq pcq-rate=0 pcq-limit=50KiB pcq-total-limit=2000KiB pcq-classifier=src-address

# 2. MANGLE RULES FOR TRAFFIC MARKING (PREROUTING & FORWARD)
/ip firewall mangle
add chain=forward action=mark-connection new-connection-mark=CONN_LOCAL_CLIENT passthrough=yes src-address=${lan} comment="NOC-QOS: Mark Client Connections"
add chain=forward action=mark-connection new-connection-mark=CONN_LOCAL_CLIENT passthrough=yes dst-address=${lan}
add chain=forward action=mark-packet new-packet-mark=PKT_DL_CLIENT passthrough=no connection-mark=CONN_LOCAL_CLIENT in-interface=${wan} comment="NOC-QOS: Mark Download Packets"
add chain=forward action=mark-packet new-packet-mark=PKT_UL_CLIENT passthrough=no connection-mark=CONN_LOCAL_CLIENT out-interface=${wan} comment="NOC-QOS: Mark Upload Packets"

# 3. PARENT & LEAF QUEUE TREES WITH BURST CALIBRATION
/queue tree
add name="PARENT_GLOBAL_DL" parent=global max-limit=${dl}M comment="NOC-QOS: Parent Download"
add name="PARENT_GLOBAL_UL" parent=global max-limit=${up}M comment="NOC-QOS: Parent Upload"

add name="QUEUE_DL_${lan.replace(/[\/\.]/g, '_')}" parent="PARENT_GLOBAL_DL" packet-mark=PKT_DL_CLIENT queue=PCQ_Download_Client priority=4 max-limit=${dl}M limit-at=${Math.floor(dl * 0.7)}M
add name="QUEUE_UL_${lan.replace(/[\/\.]/g, '_')}" parent="PARENT_GLOBAL_UL" packet-mark=PKT_UL_CLIENT queue=PCQ_Upload_Client priority=4 max-limit=${up}M limit-at=${Math.floor(up * 0.7)}M
`;

  return {
    id: `qos-pcq-${Date.now()}`,
    title: `QoS Queue Tree PCQ (${dl}M DL / ${up}M UL)`,
    category: 'qos',
    description: `Manajemen bandwidth dinamis berbasis PCQ untuk subnet ${lan} dengan prioritas paket dan pembagian adil tanpa jitter.`,
    script: script.trim(),
    safetyLevel: 'safe',
    tags: ['Queue Tree', 'PCQ', 'Bandwidth Management', 'Mangle'],
    explanation: [
      'Membagi bandwidth secara merata ke setiap host IP yang aktif di subnet LAN.',
      'Mencegah 1 pengguna menyedot seluruh kapasitas WAN (Bufferbloat mitigation).',
      'Menggunakan global parent untuk efisiensi CPU MikroTik RouterOS v6/v7.',
    ],
  };
}

/**
 * Generate MikroTik RAW Table & Firewall Filter Brute-Force & SYN Defense
 */
export function generateFirewallDefenseScript(options?: {
  wanInterface?: string;
  allowedAdminSubnet?: string;
}): GeneratedScript {
  const wan = options?.wanInterface || 'ether1';
  const adminSubnet = options?.allowedAdminSubnet || '192.168.100.0/24';

  const script = `# ================================================================
# MIKROTIK ROUTEROS - HARDENED FIREWALL & RAW ANTI-ATTACK DEFENSE
# WAN Interface   : ${wan}
# Trusted NOC LAN : ${adminSubnet}
# Generated by    : NMS-NOC AI Engine
# ================================================================

# 1. RAW TABLE: DROP BOGONS, INVALID PACKETS & SYN FLOOD AT HARDWARE SPEED
/ip firewall raw
add chain=prerouting action=drop in-interface=${wan} connection-state=invalid comment="NOC-SEC: Drop Invalid Incoming"
add chain=prerouting action=drop in-interface=${wan} tcp-flags=syn,!ack protocol=tcp connection-limit=30,32 comment="NOC-SEC: Mitigate SYN Flood"

# 2. ADDRESS LIST: TRUSTED NOC ADMINS
/ip firewall address-list
add list=NOC_TRUSTED_ADMINS address=${adminSubnet} comment="NOC-SEC: Management Subnet"

# 3. BLACKLIST BRUTE FORCE ATTACKERS (SSH, WINBOX, HTTP)
/ip firewall filter
add chain=input protocol=tcp dst-port=22,8291,80 src-address-list=NOC_BLACKLIST action=drop in-interface=${wan} comment="NOC-SEC: Drop Blacklisted Attackers"

# Stage 3 detection -> Blacklist for 7 days
add chain=input protocol=tcp dst-port=22,8291,80 in-interface=${wan} src-address-list=ATTACK_STAGE_3 action=add-src-to-address-list address-list=NOC_BLACKLIST address-list-timeout=7d comment="NOC-SEC: Add to Permanent Blacklist"
# Stage 2 detection
add chain=input protocol=tcp dst-port=22,8291,80 in-interface=${wan} src-address-list=ATTACK_STAGE_2 action=add-src-to-address-list address-list=ATTACK_STAGE_3 address-list-timeout=1m
# Stage 1 detection
add chain=input protocol=tcp dst-port=22,8291,80 in-interface=${wan} connection-state=new action=add-src-to-address-list address-list=ATTACK_STAGE_2 address-list-timeout=1m

# 4. ALLOW ESTABLISHED & RELATED CONNECTIONS
add chain=input connection-state=established,related action=accept comment="NOC-SEC: Accept Established"
add chain=input connection-state=invalid action=drop comment="NOC-SEC: Drop Invalid"
add chain=input src-address-list=NOC_TRUSTED_ADMINS action=accept comment="NOC-SEC: Accept Trusted Management"
`;

  return {
    id: `fw-defense-${Date.now()}`,
    title: 'MikroTik Hardened Firewall & Anti Brute-Force',
    category: 'firewall',
    description: `Proteksi bertingkat pada table RAW dan Filter untuk menangkal percobaan brute-force Winbox/SSH dan serangan SYN Flood.`,
    script: script.trim(),
    safetyLevel: 'medium_risk',
    tags: ['Firewall Filter', 'RAW Table', 'Brute Force Defense', 'Security'],
    explanation: [
      'Menangkap penyerang pada port 8291 (Winbox) & 22 (SSH) dan memblokirnya otomatis selama 7 hari.',
      'Menggunakan RAW table untuk drop paket invalid sebelum diproses oleh connection tracker (menghemat beban CPU).',
      'Memastikan IP management admin lokal tetap aman dan tidak terblokir.',
    ],
  };
}

/**
 * Generate TCP MSS Clamping & FastTrack CPU Optimization Script
 */
export function generateOptimizationScript(options?: {
  wanInterface?: string;
  mtu?: number;
}): GeneratedScript {
  const wan = options?.wanInterface || 'ether1';
  const mtu = options?.mtu || 1492; // Typical PPPoE or WAN MTU

  const script = `# ================================================================
# MIKROTIK ROUTEROS - FASTTRACK & TCP MSS OPTIMIZATION
# WAN Interface : ${wan}
# Target MTU    : ${mtu} (MSS Clamp: ${mtu - 40})
# Generated by  : NMS-NOC AI Engine
# ================================================================

# 1. TCP MSS CLAMPING (PREVENTS PACKET FRAGMENTATION & SLOW BROWSING)
/ip firewall mangle
add chain=forward action=change-mss new-mss=clamp-to-pmtu passthrough=yes protocol=tcp tcp-flags=syn out-interface=${wan} comment="NOC-OPT: Auto Clamp MSS to PMTU"

# 2. FASTTRACK FORWARD (HARDWARE/KERNEL ACCELERATION FOR ESTABLISHED TRAFFIC)
# Note: FastTrack bypasses queues. Only enable if CPU load is high and Queue Tree is disabled on fasttracked streams.
/ip firewall filter
add chain=forward action=fasttrack-connection connection-state=established,related comment="NOC-OPT: FastTrack Acceleration"
add chain=forward action=accept connection-state=established,related comment="NOC-OPT: Accept FastTracked"

# 3. DNS CACHE SIZE CALIBRATION
/ip dns
set cache-size=8192KiB cache-max-ttl=1d allow-remote-requests=yes
`;

  return {
    id: `opt-fasttrack-${Date.now()}`,
    title: 'FastTrack Acceleration & TCP MSS Clamp',
    category: 'optimization',
    description: `Optimalisasi performa router untuk throughput tinggi, eliminasi fragmentasi paket TCP, dan perbesaran DNS cache.`,
    script: script.trim(),
    safetyLevel: 'safe',
    tags: ['FastTrack', 'TCP MSS', 'DNS Cache', 'Performance'],
    explanation: [
      'TCP MSS Clamping mencegah web timeout akibat perbedaan MTU pada uplink ISP.',
      'FastTrack Connection mempercepat packet forwarding hingga 3-5x lipat dengan beban CPU minimal.',
      'DNS cache diperbesar hingga 8MB untuk mempercepat waktu lookup resolve domain.',
    ],
  };
}

/**
 * Generate Multi-WAN PCC Load Balancing Template
 */
export function generatePccScript(options: {
  isp1Interface: string;
  isp2Interface: string;
  isp1Gateway: string;
  isp2Gateway: string;
  lanSubnet: string;
}): GeneratedScript {
  const { isp1Interface, isp2Interface, isp1Gateway, isp2Gateway, lanSubnet } = options;

  const script = `# ================================================================
# MIKROTIK ROUTEROS - DUAL WAN PCC LOAD BALANCING (2 LINES)
# ISP 1 (WAN 1) : ${isp1Interface} (GW: ${isp1Gateway})
# ISP 2 (WAN 2) : ${isp2Interface} (GW: ${isp2Gateway})
# LAN Subnet    : ${lanSubnet}
# Generated by  : NMS-NOC AI Engine
# ================================================================

# 1. MANGLE: PCC CONNECTION MARKING
/ip firewall mangle
add chain=prerouting dst-address-type=!local in-interface-list=LAN per-connection-classifier=both-addresses:2/0 action=mark-connection new-connection-mark=ISP1_CONN passthrough=yes comment="NOC-PCC: Balance ISP1"
add chain=prerouting dst-address-type=!local in-interface-list=LAN per-connection-classifier=both-addresses:2/1 action=mark-connection new-connection-mark=ISP2_CONN passthrough=yes comment="NOC-PCC: Balance ISP2"

# 2. ROUTING MARKS
add chain=prerouting connection-mark=ISP1_CONN in-interface-list=LAN action=mark-routing new-routing-mark=to_ISP1 passthrough=yes
add chain=prerouting connection-mark=ISP2_CONN in-interface-list=LAN action=mark-routing new-routing-mark=to_ISP2 passthrough=yes

# 3. NAT MASQUERADE
/ip firewall nat
add chain=srcnat out-interface=${isp1Interface} action=masquerade comment="NOC-NAT: ISP1"
add chain=srcnat out-interface=${isp2Interface} action=masquerade comment="NOC-NAT: ISP2"

# 4. STATIC ROUTING WITH RECURSIVE FAILOVER
/ip route
add dst-address=0.0.0.0/0 gateway=${isp1Gateway} routing-table=to_ISP1 check-gateway=ping comment="NOC-RT: Route ISP1"
add dst-address=0.0.0.0/0 gateway=${isp2Gateway} routing-table=to_ISP2 check-gateway=ping comment="NOC-RT: Route ISP2"
add dst-address=0.0.0.0/0 gateway=${isp1Gateway} distance=1 check-gateway=ping comment="NOC-RT: Main Fallback ISP1"
add dst-address=0.0.0.0/0 gateway=${isp2Gateway} distance=2 check-gateway=ping comment="NOC-RT: Main Fallback ISP2"
`;

  return {
    id: `pcc-dual-wan-${Date.now()}`,
    title: 'Dual WAN PCC Load Balancing & Failover',
    category: 'failover',
    description: `Pemisahan trafik 50:50 pada dua koneksi ISP (${isp1Interface} & ${isp2Interface}) dengan mekanisme recursive failover.`,
    script: script.trim(),
    safetyLevel: 'high_risk',
    tags: ['PCC', 'Dual WAN', 'Load Balancing', 'Failover'],
    explanation: [
      'Membagi sesi koneksi menggunakan Per Connection Classifier (both-addresses).',
      'Mencegah masalah session mismatch pada login perbankan dan HTTPS.',
      'Otomatis switch jalur jika salah satu gateway ISP mengalami RTO (check-gateway=ping).',
    ],
  };
}
